### ISSUE TITLE
Not working in fish ver. 3.4.1

### ISSUE THREAD

**Issue by mumeiyamibito** [ccyip/push-line.fish#1]
In fish ver. 3.4.1, the buffer can be stacked with Alt-q, but the stacked buffer is not displayed after another command is executed.

Environment:
* LinuxMint 20.3
* Fish (https://launchpad.net/~fish-shell/+archive/ubuntu/release-3)

**Comment by ccyip** [comment]
These two issues are related:
https://github.com/fish-shell/fish-shell/issues/8824
https://github.com/fish-shell/fish-shell/issues/8807

To simply put, when you hit enter key, the new prompt will clear whatever was displayed via `commandline`. It seems you can only display a command using key bindings.

Unfortunately I have no idea how to fix that, and the fish developers said they do not plan on supporting it.

It seems to me the best thing I can do at the moment is to provide a key binding (perhaps `\cq`) so you can manually pop and display the stacked commands.

~~One solution was proposed in one of those issues. But you would need to edit your `fish_prompt` function. Perhaps I can support that too, as long as you are willing to pollute your `fish_prompt`.~~ (My bad, didn't read that comment carefully)

Anyway, I will add a key binding when I get the chance (perhaps this weekend). Sadly, I don't think we can automatically pop the commands easily anymore, unless the fish developers change their mind.

**Comment by mumeiyamibito** [comment]
Thanks for the helpful information and your support.

**Comment by ccyip** [comment]
Added a keybinding `\cq` for popping the commands.

**Comment by ccyip** [comment]
Apparently fish developers changed their mind. This plugin works again in fish version 3.5!

**Comment by mumeiyamibito** [comment]
@ccyip Thank you for your information!

The current push and restore method using two shortcut keys is also quite easy to use.
